### ISSUE TITLE
Generate metrics on spec-compliance during build and output to project website

### ISSUE THREAD

**Issue by lopopolo** [artichoke/artichoke#101]
https://news.ycombinator.com/item?id=20606476

**Comment by lopopolo** [comment]
This is unlikely to get done. Closing as WONTFIX.

**Comment by eregon** [comment]
Here is what I used to estimate the number of specs Artichoke passes:
```
$ git clone https://github.com/artichoke/artichoke.git
$ cd artichoke
$ dnf install cargo clang llvm-devel

$ cargo run -q -p spec-runner -- spec-runner/enforced-specs.yaml
Passed 1694, skipped 214, not implemented 0, failed 0 specs.
```
I split `enforced-specs.yaml` into core and library:

```
$ cargo run -q -p spec-runner -- spec-runner/core-specs.yaml
Passed 1367, skipped 202, not implemented 0, failed 0 specs.

$ cargo run -q -p spec-runner -- spec-runner/library-specs.yaml
Passed 327, skipped 12, not implemented 0, failed 0 specs.
```

And then we can compare to how many specs CRuby passes by running the specs on CRuby.
That's the approach I used for https://eregon.me/blog/2020/06/27/ruby-spec-compatibility-report.html

What would be useful is if the CI ran the specs. I don't see the specs run in e.g. https://github.com/artichoke/artichoke/runs/962372127?check_suite_focus=true

Separating core & library into different files would be more convenient, but that's easy to do manually too.

**Comment by lopopolo** [comment]
Hey @eregon thanks for sharing. I felt a bit of pride at being included in your roundup.

This approach likely significantly underestimates the number of `it` blocks Artichoke successfully passes.

`enforced-specs.yaml` corresponds to entire spec files that Artichoke passes. This is the granularity of the test harness.

Running the specs on CI is not something I'd like to do in this repository. I'd prefer to do something like `rust-toolstate` where spec pass rates are tested after every merge or daily externally -- much like how nightly and Docker builds are generated in external repos. This would enable building a custom crate and spec harness with more exhaustive testing and output more suitable for building a dashboard (JSON).

This seems to me like a lot of work that I am not interested in taking on right now.

This work is tracked in GH-142.

**Comment by eregon** [comment]
> This approach likely significantly underestimates the number of `it` blocks Artichoke successfully passes.

Do you mean Artichoke might pass spec examples that are not in the `enforced-specs.yaml`, or something else?
The first applies to all Rubies, it's always based on the include/exclude list per implementation, because some specs might fail to load at all on some Ruby implementations, or trigger a crash in the Ruby implementation.

> `enforced-specs.yaml` corresponds to entire spec files that Artichoke passes. This is the granularity of the test harness.

I see, so files with some failing examples are not included at all? That seems unfortunate, especially since it might be frequent to pass most spec examples and fail a few. Also for the matter of tracking regressions.

> Running the specs on CI is not something I'd like to do in this repository.

Completely up to you of course, and I don't know much about Artichoke CI.
But having it here would have 2 advantages: discoverability and efficient regression tracking without delay.

> This would enable building a custom crate and spec harness with more exhaustive testing and output more suitable for building a dashboard (JSON).

I understand that's a lot of work, that's why I suggested just running them in CI.
