### ISSUE TITLE
Compatibility Matrix

### ISSUE THREAD

**Issue by sempervictus** [artichoke/artichoke#1116]
As requested - filing this as a standalone issue:

Does Artichoke have an official compatibility matrix anywhere or a readout of the rubysl family tests? 
Having a running tracker against those libs should be a good way to stay aware of how and where the VMs diverge. Brian from the Rubinius project made them in part to strip that meat out of the core and in part to have a reference point for where the three major VMs of the day were in relation to each other for "standard functions."
By the way, there may be quite a few solutions to "the difficult issues around running semantic Ruby" in the Rubinius codebase - the VM is basically a set of C++ primitives (well written) with most of the VM itself _in ruby_ - so rather "portable" for other similar projects.

**Comment by lopopolo** [comment]
Thanks for the question @sempervictus.

This ticket and comment is the best way to figure out which parts of `ruby/spec` artichoke passes: https://github.com/artichoke/artichoke/pull/1088#issuecomment-779471266. These specs are not run in CI and may regress because Artichoke is best described as unstable and under major internal surgery.

Artichoke's primary goal is to replace all of the mruby core it depends on, and until that happens, the maintenance cost of automated spec compliance testing is not a cost I am willing to pay.

In the very long run, Artichoke would like to offer an [MRI-compatible API](https://github.com/artichoke/artichoke/labels/CAPI-MRI), but that is a long ways away.

Unfortunately I think my best answer is that Artichoke is not yet mature enough for me to offer the coverage and compatibility guarantees you're looking for.
