### ISSUE TITLE
Refactor `Subsec::to_tuple` to return `core::time::Duration`

### ISSUE THREAD

**Issue by lopopolo** [artichoke/artichoke#2096]
per discussion on Discord, is this better represented as `pub fn to_duration(&self) -> core::time::Duration`?

One caveat here is the `Duration` type in `core` is unsigned.

_Originally posted by @lopopolo in https://github.com/artichoke/artichoke/pull/1956#discussion_r950890146_

**Comment by b-n** [comment]
@lopopolo I'm not sure if this would be possible and/or it would lose some of it's expressiveness. As you mention, `Duration` is not signed, so this would require something like:

```rust 
pub fn to_duration(self) -> (bool, core::Duration)
```

Or relevant `try_convert_mut`.

Further, you'll see even `tz-rs` deals with these issues in the same way (I assume due to a similar reason); https://docs.rs/tz-rs/0.6.14/src/tz/datetime/mod.rs.html#84 (e.g. they aren't using Duration there either)

We could use return an offset from `std::SystemTime::UNIX_EPOCH` as a zero measure, but that would involve extra math which is already available in `spinoso-time`.

Do you have any other ideas/options?

**Comment by lopopolo** [comment]
Ahh I see. I think you've thought about this a lot more than I have 😅 and your explanation makes sense to me. Do you think we should close this ticket?

**Comment by b-n** [comment]
Hah yep. Until `core::Duration` supports `sign` :grimacing:. I'll press the close!
