### ISSUE TITLE
Re-enable all converters behind a feature flag

### ISSUE THREAD

**Issue by lopopolo** [artichoke/artichoke#349]
GH-348 disabled lots of converters for collection types to improve compilation speed.

These converters are part of the public API and should be enable-able behind a crate feature.

**Comment by vinistock** [comment]
Hey, @lopopolo! I'm a Rubyist learning some Rust and would love to help.

My understanding is that, in order to conditionally execute all the commented code depending on the crate feature, we'd need to use the feature macro and wrap the calls in a scope. Additionally, we need to add it to `Cargo.toml`. Are my assumptions correct?

Also, is there anyway of conditionally executing a group of function calls based on the feature without wrapping them in a scope?

This is what I imagine needs to be done:
```rust
#[cfg(feature = "artichoke-converters")]
{
    array_to_ruby!(HashMap<bool, Value>);
    array_to_ruby!(HashMap<bool, bool>);
    ...
}
```

Let me know your thoughts and I will gladly put together a pull request.

**Comment by lopopolo** [comment]
This looks right to me. You might need to wrap the macros in a module, but since they only impl traits that should be fine.

Let’s call the feature `artichoke-all-converters` or something like that. This feature should be disabled by default. I know this doesn’t exist today, but could you take a stab at documenting this feature in the artichoke-backend readme?

Thanks for picking this up.
