### ISSUE TITLE
Borrow from Rubinius

### ISSUE THREAD

**Issue by sandstrom** [artichoke/artichoke#713]
If I understood the plan for artichoke correctly, you're planning to implement parts of Ruby's standard library in Rust, and some parts in Ruby (at least to begin with).

If that's the case, perhaps you can borrow some code from Rubinius, since they've already implemented parts of stdlib in Ruby. For example:

- https://github.com/rubinius/rubinius/blob/master/core/random.rb
- https://github.com/rubinius/rubinius/blob/master/core/enumerable.rb

***

Another thought:

I know next to nothing about implementing VMs and programming languages. But perhaps you could engage with some of the top users of Ruby (Github, Stripe, Shopify, Heroku, etc) and see if any of them have use-cases for Ruby in WASM, for example. 

For projects like this I think it's great with 1-2 beachheads, real-world use-cases where the project is useful. And then use them to gradually expand into more areas. 

Best of luck! 💯

**Comment by lopopolo** [comment]
Hi @sandstrom thanks for the issue.

## Rubinius

I am aware of Rubinius, but have not chosen to incorporate any parts of it into Artichoke for a few reasons:

- Artichoke is currently based on mruby which has its own impls of Ruby Core classes in Ruby.
- Artichoke has sucked these classes into its Rust version of Core: https://github.com/artichoke/artichoke/issues/32.
- mruby's Core implementation has some quirks in which Core methods it chooses not to implement. Porting to Rubinius would require figuring out if these methods are required and then implementing them.
- Artichoke's current focus is to remove its dependency on mruby.

It is possible that depending on the Rubinius impls is the right thing to do in the long run, but it is not the highest priority thing to tackle now.

## Wasm

Artichoke already (ish) builds to Wasm via the emscripten target. A build is available at https://artichoke.run. The site has proven notoriously difficult to deploy -- https://github.com/artichoke/playground/pull/55 -- because the emscripten compiler is much more strict than clang and I believe there are latent segfaults or other UB in the highly modified version of mruby Artichoke embeds.

To effectively deploy to Wasm, the mruby C implementation must be removed.

## Beachheads

I spoke to a team at Shopify last summer about the possibility of rebuilding Shopify Scripts on Artichoke. I spent a good chunk of effort trying to build Artichoke on `wasm32-unknown-unknown` target with https://github.com/artichoke/artichoke/issues/54, but the Rust toolchain support wasn't there. This ticket is the reason for pushing toward the removal of the mruby dependency, see https://github.com/artichoke/artichoke/issues/54#issuecomment-590076073.

---

I hope this gives a bit more context on the motivations for what I'm working on right now. I hope you'll think it means the right work is happening.

Given that, I'm not sure this ticket is directly actionable outside of the execution plan already happening, so I'm going to close this ticket. If you feel that's not the case, please reopen it. 💎

**Comment by sandstrom** [comment]
Got it, thanks!

I just wanted to send in some ideas, but it seems like you've already given this a lot of thought. Yeah, agree close the issue! Just wanted to send along a few words.

Don't know anything about systems programming + swamped in work, so I'm afraid I cannot contribute :/ But I'll be watching this with interest! Seems like you've already made a lot of awesome progress! 🎉 

I hope you can rally more people around the project and find a great beachhead to expand from! 

In the long term, maybe it can replace MRI (who knows 🤷🏼‍♂️), that would be cool! 😄
