### ISSUE TITLE
Extend the Artichoke parser to allow emoji identifiers tracking ticket

### ISSUE THREAD

**Issue by lopopolo** [artichoke/artichoke#78]
Extend the artichoke parser to support emoji identifiers.

- investigate how feasible it is to add emoji support to mruby
- otherwise, wait for the [VM to be written in Rust](https://github.com/artichoke/artichoke/milestone/13) with a lalrpop parser which will be easier to extend.

**Comment by rurban** [comment]
But beware of the security implications then. Allowing unicode identifiers you need to normalize them, and restrict certain scripts and a bit more. 
see the unicode security guidelines for identifiers. 
* http://unicode.org/reports/tr31/
* http://unicode.org/reports/tr36/ 
* http://unicode.org/reports/tr39/

I implemented that in cperl, but it was a lot of work with no significant advantage. Most of the cool languages which added unicode identifiers are entirely insecure because of that. 
The simpliest rule: "Identifiers need to stay identifiable"

**Comment by lopopolo** [comment]
This ticket should not be necessary once #923 is adopted.
